### ISSUE TITLE
Very suitable on regression bug in Libvips (NetVips.Native 8.12.1)

### ISSUE THREAD

**Issue by AndrePScope** [kleisauke/net-vips#178]
Hello Dear NetVips!

We faced with the error message from Libvips (NetVips.Native) in the latest version (8.13.1).
The message also reproduced on 8.12.1
But not 8.11.4 !
The version NetVips.Native 8.11.4 and less works well without errors!

This is an Error message
```
Unhandled exception. NetVips.VipsException: unable to call text
text: text image too large

   at NetVips.Operation.Call(String operationName, VOption kwargs, Image matchImage, Object[] args)
   at NetVips.Operation.Call(String operationName, VOption kwargs, Object[] args)
   at NetVips.Image.Text(String text, String font, Nullable`1 width, Nullable`1 height, Nullable`1 align, Nullable`1 rgba, Nullable`1 dpi, Nullable`1 justify, Nullable`1 spacing, String fontfile)
```

This is the code:
```
using var image = Image.Text(File.ReadAllText("alice.txt"), 
				"Arial 20px",
				width: 704,
				height: null);
```

Text [alice.txt](https://github.com/kleisauke/net-vips/files/9492162/alice.txt) is attaged to request.
Was tested in different versions .Net Core / Framworks.

The result is the same. The problem in the NetVips generally is in  8.10. 

Thank you!
Andrii Pastushyn

**Comment by kleisauke** [comment]
Since you're the same reporter as https://github.com/kleisauke/net-vips/issues/129, I assume this didn't work on libvips prior version 8.12.0 either.

Commit https://github.com/libvips/libvips/commit/2cebec9a80c09002acbc00c50e7f68d4a765f982 makes `vips_text` fail to render when a dimension is larger than 32767 pixels. The above configuration (i.e., creating an image of the Alice in Wonderland novel) attempts to create a 652x86595 image which exceeds the 32k limit of Cairo. Unfortunately, this is not fixable.

**Comment by AndrePScope** [comment]
Hello @kleisauke !

>Since you're the same reporter as https://github.com/kleisauke/net-vips/issues/129, I assume this didn't work on libvips prior version 8.12.0 either.

No,no,no... That https://github.com/kleisauke/net-vips/issues/129 issue was about very-very big text.
This is does not relates to this problem.


Before 8.12.0 this works well ! Be sure. You can test https://github.com/kleisauke/net-vips/files/9492162/alice.txt and you will see.
So, in fact, this is regression.

**Comment by kleisauke** [comment]
On my Windows PC with libvips 8.11.0, I see:
```csharp
var image = Image.Text(File.ReadAllText("alice.txt")[..63648], "Arial 20px", width: 704);
Console.WriteLine(image.Width);  // 653
Console.WriteLine(image.Height); // 32767
Console.WriteLine(image.Avg());  // ~24.7

image = Image.Text(File.ReadAllText("alice.txt")[..(63648 + 1)], "Arial 20px", width: 704);
Console.WriteLine(image.Width);  // 653
Console.WriteLine(image.Height); // 32787
Console.WriteLine(image.Avg());  // 0, all black
```

So, it failed to render when a dimension is larger than 32767 pixels.

But this seems to work without any issues on libvips 8.10.6, as you mentioned:
```csharp
using var image = Image.Text(File.ReadAllText("alice.txt"), "Arial 20px", width: 704);
Console.WriteLine(image.Width);  // 653
Console.WriteLine(image.Height); // 80620
Console.WriteLine(image.Avg());  // ~24.1
```

libvips 8.11 added [support for full-colour text rendering](https://www.libvips.org/2021/06/04/What's-new-in-8.11.html#full-colour-text-rendering) via `pangocairo` instead of `pangoft2`, so I guess the previous `pangoft2` dependency didn't had this 32k dimension limit.

@jcupitt perhaps we could still use `pangoft2` for mono-rendering and only check for Cairo's 32k limit when the `rgba` flag is set?

I'm relabeling this issue as triage.

**Comment by AndrePScope** [comment]
@kleisauke, thank you very much for your time and investigation!

Hope the solution you said:
_perhaps we could still use pangoft2 for mono-rendering and only check for Cairo's 32k limit when the rgba flag is set_

Thank you in advance!

**Comment by jcupitt** [comment]
Wow, I'm amazed text worked for such large strings!

A separate path for mono rendering sounds bad in terms of maintenance, but I agree it'd fix this issue. Would it be much more code? I don't remember how large the change was when we switched to cairo.

**Comment by kleisauke** [comment]
It looks like Pango 2 removes the platform-specific drawing API in favor of Cairo, see:
https://gitlab.gnome.org/GNOME/pango/-/blob/pango2/docs/migrating.md#stop-using-non-cairo-drawing-apis

So, I'm not sure if depending on the `pango_ft2_*` APIs is the best solution.

In the meantime, I opened PR https://github.com/libvips/libvips/pull/3057 to simplify this check.

**Comment by kleisauke** [comment]
I'm removing the triage label. This 16.16 fixed-point coordinate limit of Pango cannot be circumvented without depending on the `pango_ft2_*` APIs, which is not a solution, since Pango 2 would remove that in the future. A separate FreeType path for `vips_text()` would allow the creation of large text images, but would probably also be a maintenance burden.

For now, with large text, I recommend doing `Image.Text()` in steps (e.g., for the Alice in Wonderland novel use-case above, you might consider creating an image per page)

**Comment by jcupitt** [comment]
Sorry, no, it just makes the code that enforces this limit simpler.

The limitation is comes from quite a deep part of the rendering system and cannot be avoided easily. We suggest you render your text in sections, then join them together.

**Comment by kleisauke** [comment]
I see no possibility of circumventing this 16.16 fixed-point coordinate limit of Pango. Closing as wontfix.
