### ISSUE TITLE
Occasionally crashes in some machines, .net 4.7.2,The exception type is AccessViolationException

### ISSUE THREAD

**Issue by 2738644273** [kleisauke/net-vips#221]
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at NetVips.Internal.VipsImage.NewFromMemoryCopy(IntPtr, UIntPtr, Int32, Int32, Int32, BandFormat)
   at NetVips.Image.NewFromMemoryCopy(IntPtr, UInt64, Int32, Int32, Int32, BandFormat)
   at MatchingOptimization.Film.DicomUtils.DCMConvertToNetImage(Dicom.DicomDataset, System.Nullable`1<Double>, System.Nullable`1<Double>, Double ByRef, Double ByRef)
   at MatchingOptimization.Film.DicomUtils+<>c__DisplayClass8_1.<DrawImage>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by kleisauke** [comment]
Are you able to provide a complete, standalone code sample that allows someone else to reproduce this issue?

I suspect this could be a `.Dispose()`/reference-count bug, you need to make sure the image is not disposed too early.

**Comment by kleisauke** [comment]
@2738644273 Were you able to make any progress with this?

**Comment by kleisauke** [comment]
Closing due to inactivity but please feel free to reopen with more details if further help is required.
