### ISSUE TITLE
Trying to run on macos using blazor provides missing dll issue

### ISSUE THREAD

**Issue by justasxz** [kleisauke/net-vips#240]
Hi,

So I am trying to build the application (that already runs on windows) on mac, it builds successfully everything seems to work, but when the application opens up it throws netvips.dll exception. Is there any fix to this ? I have all the native-arm packages installed. It only fails when it tries to run netvips code, it functions normally besides that. I am running VS Code blazor hybrid

**Comment by kleisauke** [comment]
Did you see https://github.com/kleisauke/net-vips/issues/189#issuecomment-1408407451 ?

> I have all the native-arm packages installed.

You could try to install the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native/) NuGet package, it will automatically choose the appropriate NetVips.Native.* package based on which OS/bitness it's running on. This can be useful for cross-platform deployments.

**Comment by justasxz** [comment]
> Did you see [#189 (comment)](https://github.com/kleisauke/net-vips/issues/189#issuecomment-1408407451) ?
> 
> > I have all the native-arm packages installed.
> 
> You could try to install the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native/) NuGet package, it will automatically choose the appropriate NetVips.Native.* package based on which OS/bitness it's running on. This can be useful for cross-platform deployments.

Thanks, for quick reply. Yes I tried various combinations such as netvips and netvips.native only. netvips native and arm64 version at the same time. Only arm64 version, neither works. Here is the full error:

Exception has occurred: CLR/System.DllNotFoundException

Exception thrown: 'System.DllNotFoundException' in NetVips.dll: 'libvips.so.42'
   at NetVips.Internal.Vips.Init(String argv0)
   at NetVips.NetVips.Init()
   at NetVips.ModuleInitializer.Initialize()
   at .cctor()
   at PSPerformance.Domain.Editor.EditorImage.<LoadImage>b__33_0() in /Users/diana/Documents/ProSystemos/PSPerformance/PSPerformance.Domain/Editor/EditorImage.cs:line 66
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(Object workItem, Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(Object workItem, Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerDoWork(PortableThreadPool threadPoolInstance, Boolean& spinWait)
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartHelper.RunWorker()
   at System.Threading.Thread.StartHelper.Run()
   at System.Threading.Thread.StartCallback()
   
   
   If that helps I had similar issue with MagickNet until I added this to my csproj
   <MagickCopyNativeMacOS>true</MagickCopyNativeMacOS>
   
   Just to reiterate this is blazor hybrid project (so basically maui + blazor)
It works fine on windows, just on macos keeps throwing that error. I have not tried, but I believe manually adding the dll might help ?

**Comment by kleisauke** [comment]
On macOS, it should look for `libvips.42.dylib` instead of `libvips.so.42`. Could you try updating to the release candidates of NetVips 3.0.0 and NetVips.Native v8.16.0?
https://www.nuget.org/packages/NetVips/3.0.0-rc1
https://www.nuget.org/packages/NetVips.Native/8.16.0-rc1

If that works, it seems that the wrong NetVips DLL for Linux (from the `runtimes/unix/lib/netstandard2.0` directory) is being used on macOS, when it should be loading the macOS-specific DLL (from the `runtimes/osx/lib/netstandard2.0` directory) instead. Fortunately, after commit 14480400ce17a1bbb48c74e718f4d05f50e11e49, only a single DLL is now required, with re-mapping handled at runtime using [`NativeLibrary.SetDllImportResolver()`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver).

**Comment by justasxz** [comment]
> On macOS, it should look for `libvips.42.dylib` instead of `libvips.so.42`. Could you try updating to the release candidates of NetVips 3.0.0 and NetVips.Native 8.16.0? https://www.nuget.org/packages/NetVips/3.0.0-rc1 https://www.nuget.org/packages/NetVips.Native/8.16.0-rc1
> 
> If that works, it seems that the wrong NetVips DLL for Linux (from the `runtimes/unix/lib/netstandard2.0` directory) is being used on macOS, when it should be loading the macOS-specific DLL (from the `runtimes/osx/lib/netstandard2.0` directory) instead. Fortunately, after commit [1448040](https://github.com/kleisauke/net-vips/commit/14480400ce17a1bbb48c74e718f4d05f50e11e49), only a single DLL is now required, with re-mapping handled at runtime using [`NativeLibrary.SetDllImportResolver()`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver).

I updated it to the newest versions but I seem to be getting the same issue. To clarify the target is maccatalyst. I don't think you can target macOS directly on blazor hybrid. Unless I am missing something.

**Comment by kleisauke** [comment]
It appears that this issue is related to https://github.com/dotnet/runtime/issues/104160. As a workaround, you could try symlinking or renaming `libvips.42.dylib` to `libvips.so.42`, although I'm unsure if this would work on Mac Catalyst without further adjustments.

Additionally, I'm uncertain whether NetVips, or any other that relies on unmanaged/native code, would function correctly in a Blazor Hybrid environment. It's probably unsupported in Blazor components, as P/Invoke isn't natively supported there.

**Comment by kleisauke** [comment]
@justasxz Are you able to test commit 8308801dd52e84a6769b688019193b3d02fdab09? Testing can be done by using the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 3.0.0 (build number 605 - prerelease).

**Comment by kleisauke** [comment]
Hmm, looking at [`PortableRuntimeIdentifierGraph.json`](https://github.com/dotnet/runtime/blob/2c471afb09122433dc8137a9827e47ff8cedd6ff/src/libraries/Microsoft.NETCore.Platforms/src/PortableRuntimeIdentifierGraph.json), I'm unsure if the above commit will work with the `NetVips.Native*` packages, since the `maccatalyst` RIDs inherit from `ios` rather than `osx`.

```mermaid
graph TD;
    unix --> unix-x64 & ios & unix-arm64;
    unix-x64 --> ios-x64;
    unix-arm64 --> ios-arm64;
    ios --> ios-x64 & maccatalyst & ios-arm64;
    ios-x64 & maccatalyst --> maccatalyst-x64;
    ios-arm64 & maccatalyst --> maccatalyst-arm64;
```

**Comment by justasxz** [comment]
> @justasxz Are you able to test commit [8308801](https://github.com/kleisauke/net-vips/commit/8308801dd52e84a6769b688019193b3d02fdab09)? Testing can be done by using the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
> 
> ```
> <packageSources>
>   <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
> </packageSources>
> ```
> 
> And update NetVips to 3.0.0 (build number 605 - prerelease).

I would for sure be able to, I greatly appreciate your effort to add support to maccatalyst. But you just responded that you doubt it would work. Do you want me to test it or wait for another commit ?

**Comment by kleisauke** [comment]
> Do you want me to test it or wait for another commit ?

Feel free to test that commit; hopefully it will now look for `libvips.42.dylib` instead of `libvips.so.42`.

Support for iOS (and .NET MAUI) is being tracked in issue #154.

**Comment by kleisauke** [comment]
@justasxz Were you able to make any progress with this?

**Comment by justasxz** [comment]
Hi, sorry it was put on hold for a bit, I will get back to it when I can. I was having trouble downloading the preview version (never done it, and following tutorials, adding the link you provided into .nuget file did not allow me to pick preview version, might be me not knowing how to, might be just visual studio code, not working as intended), and then some other things came up with higher priority. Should come back with an answer in a few weeks if I get it working.

**Comment by kleisauke** [comment]
I'm removing the triage label as I lack access to a macOS (or iOS) device, making it difficult to debug further.

**Comment by justasxz** [comment]
Hi, I tried with the latest version and what seems to be an error changed slightly to: 

Exception has occurred: CLR/System.DllNotFoundException
* 
Exception thrown: 'System.DllNotFoundException' in NetVips.dll: 'libvips-42.dll'
   at NetVips.Internal.Vips.Init(String argv0)
   at NetVips.NetVips.Init()
   at NetVips.ModuleInitializer.Initialize()
   at .cctor()
   at PSPerformance.Domain.Editor.EditorImage.<LoadImage>b__38_0() in /Users/diana/Documents/ProSystemos/PSPerformance/PSPerformance.Domain/Editor/EditorImage.cs:line 73
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(Object workItem, Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(Object workItem, Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerDoWork(PortableThreadPool threadPoolInstance, Boolean& spinWait)
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartHelper.RunWorker()
   at System.Threading.Thread.StartHelper.Run()
   at System.Threading.Thread.StartCallback()

**Comment by justasxz** [comment]
Changing version to 3.0.0.5 gives similar error, but its still similar:

Exception has occurred: CLR/System.DllNotFoundException
Exception thrown: 'System.DllNotFoundException' in NetVips.dll: 'libvips-42.dll'
   at NetVips.Internal.Vips.Init(String argv0)
   at NetVips.NetVips.Init()
   at NetVips.ModuleInitializer.Initialize()
   at .cctor()
   at PSPerformance.Domain.Editor.EditorImage.<>c__DisplayClass41_0.<LoadImage>b__0() in /Users/diana/Documents/test-2/PSPerformance/PSPerformance.Domain/Editor/EditorImage.cs:line 145
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(Object workItem, Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(Object workItem, Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerDoWork(PortableThreadPool threadPoolInstance, Boolean& spinWait)
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartHelper.RunWorker()
   at System.Threading.Thread.StartHelper.Run()
   at System.Threading.Thread.StartCallback()


any advice or further instructions

**Comment by justasxz** [comment]
Actually what I noticed is that. If I go to 2.4.2 version the error mentions .so file if I go to 3.0.0 or 3.0.0.605 it is complaining about not finding .dll

**Comment by justasxz** [comment]
I know it's a bit weird, but I could even give you remote access to a mac if that helps you out to test. If that's something you would be needing. As I am currently really failing to understand the next possible steps, I even attempted to add NetVips as a project instead of nuget, but it still errors out with the same mistake before even reaching that method where it checks if it macos :/ Or it's not loading symbols :/

**Comment by justasxz** [comment]
I tried the first workaround 

  <MtouchExtraArgs>-gcc_flags -v</MtouchExtraArgs>
   <_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>

And it had no effect. I also attempted calling 

NetVips.ModuleInitializer.Initialize(); from static method and its still the same issue.

Thank you for your suggestions.

Also since you are helping me out and you will be paying for mac mini, do you have a Patreon or a donation page, so can I at least repay you a little.

**Comment by kleisauke** [comment]
Commit 0fa851c52aea0441466662d57099c1c05e4e83c0 ensures the correct library will be loaded on all Apple platforms. You can test this with:
```console
$ dotnet nuget add source https://ci.appveyor.com/nuget/net-vips -n netvips-nightly
$ dotnet add package NetVips -v 3.0.0.619-develop
```

This fix will be in v3.0.1.

It works when targeting `maccatalyst-arm64`, but you also need to add:
```xml
<ItemGroup>
    <PackageReference Include="NetVips.Native.osx-arm64" Version="8.16.1" GeneratePathProperty="true" />
    <NativeReference Include="$(PkgNetVips_Native_osx-arm64)/runtimes/osx-arm64/native/libvips.42.dylib">
        <Kind>Dynamic</Kind>
        <SmartLink>False</SmartLink>
    </NativeReference>
</ItemGroup>
```

To your `*.csproj` file, this ensures .NET MAUI is aware of the native libvips library.

> ```console
> Exception has occurred: CLR/System.DllNotFoundException
> Exception thrown: 'System.DllNotFoundException' in NetVips.dll: 'libvips-42.dll'
>   at NetVips.Internal.Vips.Init(String argv0)
>   at NetVips.NetVips.Init()
>   at NetVips.ModuleInitializer.Initialize()
> ...
> ```

Note that this error is a bit misleading. See for example:
<details>
  <summary>Details</summary>

```csharp
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static class Initializer
{
    [DllImport("libvips-42.dll", CallingConvention = CallingConvention.Cdecl,
        EntryPoint = "vips_init")]
    internal static extern int Init([MarshalAs(UnmanagedType.LPStr)] string argv0);

    [ModuleInitializer]
    public static void Initialize()
    {
        Console.WriteLine("Module initializer executed!");

        NativeLibrary.SetDllImportResolver(typeof(Initializer).Assembly, (libraryName, assembly, searchPath) =>
        {
            Console.WriteLine($"DllImportResolver called for {libraryName}");
            if (libraryName == "libvips-42.dll")
            {
                var rv = NativeLibrary.Load("libvips.42.dylib", assembly, searchPath);
                Console.WriteLine($"Tried to load library: {rv}");
                return rv;
            }

            return IntPtr.Zero;
        });

        try
        {
            var ret = Init("NetVips");
            Console.WriteLine($"✅ Success: {ret}");
        }
        catch (Exception e)
        {
            Console.WriteLine($"❌ FAILED: {e}");
        }
    }
}
```

```console
Module initializer executed!
DllImportResolver called for libvips-42.dll
❌ FAILED: System.DllNotFoundException: libvips-42.dll
  at NetVipsApp.Initializer.Initialize() in /Users/m1/NetVipsApp/Platforms/MacCatalyst/Program.cs:line 31
```
</details>

You'd expect it to display an error mentioning the `libvips.42.dylib` library in this case.

> Also since you are helping me out and you will be paying for mac mini, do you have a Patreon or a donation page, so can I at least repay you a little.

Financial contributions to help improve the libvips ecosystem are always welcome via https://opencollective.com/libvips.

**Comment by justasxz** [comment]
I updated to latest commit and it works. Thank you for your support. I am very grateful. Quick note for others that will want to reference this in the future. <NativeReference> is not supported on .net8 only in .net framework so I got the same result by just using <None> with including the same package. Hopefully in the future we can find a more elegant solution, but this is great for now. Thank you again.  (also quick note  AddAlpha() does not work on mac, as it returns error parameter not found if you want to look into it, we have a workaround so it's not an issue, but might as well mention it). 

I am closing it as I feel it's resolved now. 

P.S.

You are awesome.

**Comment by kleisauke** [comment]
> note AddAlpha() does not work on mac, as it returns error parameter not found

Should be fixed with commit bd664648a4285c8f3d03a738fc078239f46ce7ec. Thanks for reporting this!

**Comment by kleisauke** [comment]
> is not supported on .net8 only in .net framework

For reference, I assume you're referring to this build error:

```console
/usr/local/share/dotnet/sdk/9.0.202/Microsoft.Common.CurrentVersion.targets(2315,5): error MSB4803: The task "ResolveNativeReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details.
```

If so, you can resolve it by updating your `*.csproj` file as follows:

```xml
<ItemGroup>
    <PackageReference Include="NetVips.Native.osx-arm64" Version="8.16.1" GeneratePathProperty="true" />
    <None Include="$(PkgNetVips_Native_osx-arm64)/runtimes/osx-arm64/native/libvips.42.dylib">
        <Pack>true</Pack>
        <PackagePath>runtimes/maccatalyst-arm64/native</PackagePath>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
</ItemGroup>
```

**Comment by kleisauke** [comment]
[NetVips v3.0.1](https://www.nuget.org/packages/NetVips/3.0.1) is now available.
