### ISSUE TITLE
Can't remove metadata "icc-profile-data" on shared image

### ISSUE THREAD

**Issue by kDanil** [kleisauke/net-vips#56]
Hi,

I'm testing with recent version
https://github.com/kleisauke/net-vips/issues/55

and have a new exception this time.

NetVips 1.2.0
NetVips.Native 8.9.1

```
NetVips.VipsException: unable to call icc_transform
vips__file_open_read: unable to open file "" for reading
unix error: No such file or directory
profile_load: unable to load profile ""

   at NetVips.Operation.Call(String operationName, VOption kwargs, Image matchImage, Object[] args)
   at NetVips.Image.IccTransform(String outputProfile, String pcs, String intent, Nullable`1 embedded, String inputProfile, Nullable`1 depth)
```

**Comment by kleisauke** [comment]
There's [a breaking change](https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html#breaking-changes) within libvips 8.9 that enforces you to use [`Copy()`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_Copy_) before altering metadata. For example, this example code (which is perhaps the code that you use?):
```csharp
const string vipsMetaIccName = "icc-profile-data";

// Image source: https://images.weserv.nl/zebra.jpg
var im = Image.NewFromFile("zebra.jpg", access: "sequential");

// Increase reference count of the image (i.e. make a shared image)
im = im.Crop(0, 0, 100, 100);

// Remove embedded ICC profile, if any
if (im.Contains(vipsMetaIccName))
{
    var result = im.Remove(vipsMetaIccName);
    if (!result)
    {
        throw new VipsException("could not remove embedded ICC profile");
    }
}

// Force srgb for all images
im = im.IccTransform("srgb", inputProfile: "srgb");
```

Needs a `Copy()` before removing the embedded ICC profile, like this:
```diff
@@ -9,6 +9,9 @@ im = im.Crop(0, 0, 100, 100);
 // Remove embedded ICC profile, if any
 if (im.Contains(vipsMetaIccName))
 {
+    // Use Copy() to get a unique image before altering metadata
+    im = im.Copy();
+
     var result = im.Remove(vipsMetaIccName);
     if (!result)
     {

```

Note that you don't have to remove the embedded ICC profile, you could also just set the `embedded` parameter within [`IccTransform`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_IccTransform_) to `false`, like this:
```diff
@@ -6,18 +6,5 @@ var im = Image.NewFromFile("zebra.jpg", access: "sequential");
 // Increase reference count of the image (i.e. make a shared image)
 im = im.Crop(0, 0, 100, 100);

-// Remove embedded ICC profile, if any
-if (im.Contains(vipsMetaIccName))
-{
-    // Use Copy() to get a unique image before altering metadata
-    im = im.Copy();
-
-    var result = im.Remove(vipsMetaIccName);
-    if (!result)
-    {
-        throw new VipsException("could not remove embedded ICC profile");
-    }
-}
-
 // Force srgb for all images
-im = im.IccTransform("srgb", inputProfile: "srgb");
+im = im.IccTransform("srgb", inputProfile: "srgb", embedded: false);
```

**Comment by kDanil** [comment]
Thank you, I somehow missed breaking change in release comments.
